- name: "good first issue"
  color: "#7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "#008672"

- name: "bug"
  color: "#d73a4a"
  description: "Something isn't working"
- name: "enhancement"
  color: "#a2eeef"
  description: "New feature or request"

- name: "duplicate"
  color: "#cfd3d7"
  description: "This issue or pull request already exists"
- name: "wait"
  color: "#d876e3"
  description: "This depends on something else"
- name: "wontfix"
  color: "#ffffff"
  description: "This bug or feature request will not be worked on"

- name: "documentation"
  color: "#0075ca"
  description: "Improvements or additions to documentation"

- name: "ci"
  color: "#dce3b5"
- name: "dependabot"
  color: "#5e86d7"
