- name: "bug"
  color: "#d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "#0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "#cfd3d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "#a2eeef"
  description: "New feature or request"
- name: "good first issue"
  color: "#7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "#008672"
- name: "wontfix"
  color: "#ffffff"
  description: "This bug will not be worked on"
- name: "dependabot"
  color: "#5e86d7"
- name: "low prio"
  color: "#1d76db"
- name: "wontdo"
  color: "#bfdadc"
  description: "This feature request will not be worked on"
- name: "wip"
  color: "#e4e669"
  description: "The issue description is a work in progress"
- name: "wait"
  color: "#d876e3"
  description: "This depends on something else"
