changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Bugs fixed
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: CI
      labels:
        - ci
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependabot
    - title: Dependencies
      labels:
        - dependabot
